apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: image-compressor
  labels:
    app: backend
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http
  selector:
    app: backend
  type: ClusterIP
