apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: image-compressor
  labels:
    app: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: frontend
  type: ClusterIP

  