apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: image-compressor
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nikolajkoko/image-compressor-frontend:github-latest  # Replace with your actual image
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"