apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: image-compressor
type: Opaque
data:
  POSTGRES_USER: YWRtaW5fdXNlcg==       # base64 of 'admin_user'
  POSTGRES_PASSWORD: YWRtaW4=           # base64 of 'admin'
